# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d27d8dffc0ba857c1e53b1ba8237b1f8e0cd64e0c6f9ff0c63aa150681b8e68075e5864cf5bfcdfb401fcb7da5d088decc0b6ac96f69f83c4edb3d89a0378d2
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_api_key: <%= ENV["MANDRILL_API_KEY"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>

test:
  secret_key_base: 350bbde84c99952217b5a259b23196b8a828e0c2e5e2e1c622c228e7bc7f93002177c0163aa801baee5df47ca5e82a0b172aed5d1d46a000d1ee34b3f1140b99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
